configMapGenerator:
  - name: listmonk-statics
    envs:
      - configs.env
  - name: listmonk-statics-files
    files:
      - robots.txt
  - name: listmonk-statics-config
    files:
      - config.toml

resources:
  - service.yml
  - deployment.yml
  - httproute.yml
  - ciliumnetworkpolicy.yml

images:
  - name: ghcr.io/static-web-server/static-web-server
    newTag: "2"
  - name: curlimages/curl
    newTag: 8.17.0

commonLabels:
  app.kubernetes.io/name: listmonk-statics
  app.kubernetes.io/instance: listmonk-statics
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: listmonk-statics
  app.kubernetes.io/part-of: listmonk-statics
  app.kubernetes.io/version: 2-alpine

replacements:
  - source:
      kind: Deployment
      name: listmonk-statics
      fieldPath: spec.template.metadata.labels
    targets:
      - select:
          kind: Service
          name: listmonk-statics
        fieldPaths:
          - spec.selector
        options:
          create: true
      - select:
          kind: CiliumNetworkPolicy
          name: listmonk-statics
        fieldPaths:
          - spec.endpointSelector.matchLabels
        options:
          create: false

namespace: default
